---
os: linux

language: python

python:
  - '3.7'

jobs:
  include:
    - os: linux
      dist: bionic
    - os: linux
      dist: xenial

before_script:
  - chmod +x testme.sh

script:
  - sudo /bin/bash -H -c './testme.sh -i -k'